### PR TITLE
Update CV_bridge

### PR DESCRIPTION
**Pull request by talregev**
Update CV_bridge:
- CV Bridge work without OpenCV Manager.
- Remove opencv - It now take from maven.

Update all apps:
- Use android_core_components.
- Add FOREGROUND_SERVICE permission for android Pie (Android 9).
- minSdkVersion 16
- targetSdkVersion 28

### CODE REVIEW

**Comment by jubeira** [comment]
Thanks again @talregev! I'd like to give it a shot before approving; I'll do so as soon as I can.

**Comment by talregev** [comment]
@jubeira 
I am running the apps on ros melodic, and I am able to get the images msgs, but not send them. It not doing any exception, the program run, but I didn't get the image msgs over the topics.  I am not sure if it because I am using ros melodic. if the problem is not from ros melodic, i am not know what is the problem. Can you help / verify it?

**Review by jubeira — APPROVED** [review]
Thanks @talregev!

For the record, @rjcausarano gave this a shot and it worked with Melodic. He had to set `ROS_IP` variable to publish messages from the PC to the app -which is expected-, but other than that it works out of the box. Thanks!

**Comment by talregev** [comment]
Thanks for verify for me! :)
For me it also work on ros melodic, I was needed to do hotspot the phone with the computer.

**Pull request merged**
